version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://bitrix24_user:bitrix24_password@db:5432/bitrix24_ai_assistant
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    networks:
      - bitrix24_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=bitrix24_ai_assistant
      - POSTGRES_USER=bitrix24_user
      - POSTGRES_PASSWORD=bitrix24_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - bitrix24_network

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - bitrix24_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - bitrix24_network

volumes:
  postgres_data:
  redis_data:

networks:
  bitrix24_network:
    driver: bridge
